### ISSUE TITLE
WebDAV pdf isn’t working 

### ISSUE THREAD

**Issue by Loooookk** [trilliaapp/zoterouploader#2]
Hello,I am very happy when I find this app because it give a solution for my Zotero item generation.

but I have some questions and need you help.

here is my description of my question 

When I use zotero to sync file, fine! I can open the attachment.
When I use WebDAV to sync file, emmm….,I can’t open the attachment. The app show that “the attached file is not available on the WebDAV server.please check that the file has synced on the. Device where it was added”

thank for your help!

**Comment by trilliaapp** [comment]
Thank you for reporting the WebDAV issue. We will look into it and will update this thread.

**Comment by Loooookk** [comment]
> Thank you for reporting the WebDAV issue. We will look into it and will update this thread.

Looking forward to the new version.

Thank you very much!

**Comment by trilliaapp** [comment]
Hi,

The new version of the app (1.9) should now support WebDAV (see option in the settings). Please, reopen this issue if it doesn't work for you.

Thank you

**Comment by Loooookk** [comment]
Oh!! It is working! Thank you very much!

**Comment by moritz-schwarz** [comment]
Does it also work with Koofr? Koofr does work well with Zotero (via WebDAV). But I cannot make it run with your app. Do I perhaps need to use the exact same app password as Zotero? It does not work with a new password and before I reset Zotero's app password for Koofr, I would like to know if your app for some reason does not work with Koofr.

https://app.koofr.net/dav/Koofr/zotero/ would be the URL, correct?

**Comment by trilliaapp** [comment]
Hi moritz-schwarz,

Apologies for the delay. This should be fixed in the next version (hopefully uploaded by tomorrow or Tuesday).

The settings should be:
- URL: https://app.koofr.net/dav/koofr (no need to add zotero at the end)
- Username: [email address you used to create your Koofr account]
- Password: [[app specific password generated via Koofr]](https://koofr.eu/help/koofr_with_webdav/how-do-i-connect-a-service-to-koofr-through-webdav/)
